export const skills = {
  technical: [
    "JavaScript",
    "TypeScript",
    "React.js",
    "Next.js",
    "HTML5/CSS",
    "Node.js",
    "Tailwind",
    "Redux",
    "Git",
    "REST APIs",
    "MongoDB",
    "MySQL",
    "Docker",
    "Clean Architecture",
    "Testing",
  ],
  softs: [
    "Effective Communication",
    "Leadership",
    "Problem Solving",
    "Teamwork",
    "Adaptability",
    "Continuous Learning",
    "Time Management",
    "Empathy",
  ],
};
